import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })
import Provider from './Provider'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex min-h-screen flex-row'>
          <div className='flex-1'>
            <Provider>
              {children}
            </Provider>
          </div>
        </div>
      </body>
    </html>
  )
}
